version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27027:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webcastle-backend
    restart: always
    ports:
      - "3432:3432"
    depends_on:
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/webcastle
      - DB_CONNECTION_STRING_LOCAL=mongodb://mongodb:27017/webcastle
      - PORT=3432
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: webcastle-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3432/api
      - BACKEND_URL=http://backend:3432
      - AUTH_TRUST_HOST=true
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge